import { basename, dirname, extname, join } from "node:path";
import { readdirSync, writeFileSync } from "node:fs";

import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const UI_COMPONENTS_DIRECTORY = join(scriptDirectory, "..", "src", "primitives");
const GENERATED_UI_COMPONENTS_INDEX = join(UI_COMPONENTS_DIRECTORY, "generated.ts");
const SOURCE_FILE_EXTENSIONS = new Set([".ts", ".tsx"]);

const componentModulePaths = readdirSync(UI_COMPONENTS_DIRECTORY, { withFileTypes: true })
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((fileName) => SOURCE_FILE_EXTENSIONS.has(extname(fileName)))
    .filter((fileName) => !fileName.endsWith(".d.ts"))
    .filter((fileName) => fileName !== "index.ts" && fileName !== "generated.ts")
    .map((fileName) => basename(fileName, extname(fileName)))
    .sort((left, right) => left.localeCompare(right));


const barrelFileContents = [
    "// This file is auto-generated by scripts/sync-exports.mjs.",
    ...componentModulePaths.map((componentModulePath) => `export * from "./${componentModulePath}";`),
    ""
].join("\n");

writeFileSync(GENERATED_UI_COMPONENTS_INDEX, barrelFileContents);
