import { basename, dirname, extname, join } from "node:path";
import { readdirSync, writeFileSync } from "node:fs";

import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const CORE_DIRECTORY = join(scriptDirectory, "..", "src", "core");
const CATEGORIES = ["atoms", "molecules", "organisms"];
const SOURCE_FILE_EXTENSIONS = new Set([".ts", ".tsx"]);

function generateExportsForCategory(category) {
    const categoryDirectory = join(CORE_DIRECTORY, category);
    const indexPath = join(categoryDirectory, "index.ts");

    const componentModulePaths = readdirSync(categoryDirectory, { withFileTypes: true })
        .filter((entry) => entry.isFile())
        .map((entry) => entry.name)
        .filter((fileName) => SOURCE_FILE_EXTENSIONS.has(extname(fileName)))
        .filter((fileName) => !fileName.endsWith(".d.ts"))
        .filter((fileName) => fileName !== "index.ts")
        .map((fileName) => basename(fileName, extname(fileName)))
        .sort((left, right) => left.localeCompare(right));

    const barrelFileContents = [
        "// This file is auto-generated by scripts/sync-exports.mjs.",
        ...componentModulePaths.map((componentModulePath) => `export * from "./${componentModulePath}";`),
        ""
    ].join("\n");

    writeFileSync(indexPath, barrelFileContents);
    console.log(`Generated ${category} exports (${componentModulePaths.length} components)`);
}

// Generate exports for each category
CATEGORIES.forEach(generateExportsForCategory);

// Generate main core index.ts
const coreIndexPath = join(CORE_DIRECTORY, "index.ts");
const coreIndexContents = [
    "// This file is auto-generated by scripts/sync-exports.mjs.",
    ...CATEGORIES.map((category) => `export * from "./${category}";`),
    ""
].join("\n");

writeFileSync(coreIndexPath, coreIndexContents);
console.log("Generated core/index.ts exports");
