import type { ClientRecord } from "./types"

export const clients: ClientRecord[] = [
    {
        id: "CL-0001",
        name: "Atlas SARL",
        legalForm: "SARL",
        ice: "001234567800001",
        regime: "normal",
        status: "active",
        monthlyRevenueMad: 128450,
        monthlyRevenueDeltaPct: 6.8,
        pendingDeclarations: 1,
        pendingDeclarationsDelta: -1,
        unreconciledEntries: 7,
        unreconciledEntriesDelta: -4,
        employeeCount: 14,
        employeeCountDelta: 1,
        lastUpdatedAt: "2026-04-24",
    },
    {
        id: "CL-0002",
        name: "Noura Consulting",
        legalForm: "SUARL",
        ice: "001234567800002",
        regime: "simplified",
        status: "review",
        monthlyRevenueMad: 84200,
        monthlyRevenueDeltaPct: 2.1,
        pendingDeclarations: 2,
        pendingDeclarationsDelta: 0,
        unreconciledEntries: 11,
        unreconciledEntriesDelta: -2,
        employeeCount: 6,
        employeeCountDelta: 0,
        lastUpdatedAt: "2026-04-22",
    },
    {
        id: "CL-0003",
        name: "Maghreb Logistics",
        legalForm: "SA",
        ice: "001234567800003",
        regime: "normal",
        status: "pending_vat",
        monthlyRevenueMad: 233900,
        monthlyRevenueDeltaPct: -1.4,
        pendingDeclarations: 3,
        pendingDeclarationsDelta: 1,
        unreconciledEntries: 19,
        unreconciledEntriesDelta: 3,
        employeeCount: 41,
        employeeCountDelta: 2,
        lastUpdatedAt: "2026-04-20",
    },
    {
        id: "CL-0004",
        name: "Rimal Trading",
        legalForm: "SARL",
        ice: "001234567800004",
        regime: "normal",
        status: "overdue",
        monthlyRevenueMad: 56300,
        monthlyRevenueDeltaPct: -4.9,
        pendingDeclarations: 5,
        pendingDeclarationsDelta: 2,
        unreconciledEntries: 28,
        unreconciledEntriesDelta: 5,
        employeeCount: 9,
        employeeCountDelta: -1,
        lastUpdatedAt: "2026-04-16",
    },
]

export function getClientById(id: string): ClientRecord | null {
    return clients.find((client) => client.id === id) ?? null
}
